"""Two-account contribution analysis, each under its correct config/schedule/tax.

  Tax-advantaged : $100k start + $35k/yr  -> config D (dual-signal + stop), pre-tax
  Taxable        : $10k  start + $2k/mo   -> config C (dual-signal, no stop), after-tax

Rolling windows at 5/10/26yr horizons, 3x ^NDX, S&P signal. Reports the MEDIAN
window (typical) and the WORST window by money-weighted ROI (the unluckiest
start — bought in right before a crash). Median is what usually happens; the
worst row is the tail you must be able to sit through.

Writes docs/dca-contribution-analysis-2026-08-28.md.

Run manually:
    python backtest/dca_contribution_analysis.py
"""
import sys
import warnings
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
from backtest.strat_backtest import run_experiment_suite, warmup_aware_start_dates
from backtest.trailing_stop_dual_breach import DualSignalSingleStop

OUTPUT_PATH = REPO_ROOT / "docs" / "dca-contribution-analysis-2026-08-28.md"

CONFIG = {"name": "3x", "leverage": 3, "expense": 0.0095}
ATR, STOP_PCT, STOP_COOL = 2.5, 0.08, 60
HORIZONS = (5, 10, 26)

# (label, strategy, initial_fund, annual_dca, monthly_dca, apply_tax)
ACCOUNTS = [
    ("Tax-adv (D, +stop)",
     DualSignalSingleStop(atr_multiplier=ATR, t2_confirmation=False, tag="GSPC",
                          trailing_stop_pct=STOP_PCT, trailing_stop_cooldown_days=STOP_COOL),
     100000, 35000, 0, False),
    ("Taxable (C, no stop)",
     DualSignalSingleStop(atr_multiplier=ATR, t2_confirmation=False),
     10000, 0, 2000, True),
]


def col(df, s, suf):
    return df[f"{s.name} {suf}"]


def run_account(strat, years, initial, adca, mdca, tax, start_dates):
    res = run_experiment_suite(
        configs=[CONFIG], strategies=[strat], start_dates=start_dates,
        period_years=years, base_ticker="^NDX", signal_ticker="^GSPC",
        annual_dca=adca, monthly_dca=mdca, initial_fund=initial,
        apply_tax=tax, print_summary=False)
    return res[CONFIG["name"]]


def main():
    warnings.filterwarnings("ignore")

    median_rows = []
    worst_rows = []
    for years in HORIZONS:
        sd = warmup_aware_start_dates(["^NDX", "^GSPC"], years)
        for label, strat, initial, adca, mdca, tax in ACCOUNTS:
            df = run_account(strat, years, initial, adca, mdca, tax, sd)
            fv, roi = col(df, strat, "Final Value"), col(df, strat, "Total ROI (%)")
            inv, dd = col(df, strat, "Total Invested"), col(df, strat, "Max DD (%)")
            twr = col(df, strat, "TWR (%)")
            n = len(df)

            median_rows.append(
                f"| {label} | {years}yr | {n} | ${inv.median():,.0f} | ${fv.median():,.0f} "
                f"| {roi.median():.0f}% | {dd.min():.1f}% | {twr.mean():.2f}% |")

            # Worst window = lowest money-weighted ROI (unluckiest entry timing).
            w = df.loc[roi.idxmin()]
            wdate = str(w["Start Date"])[:10]
            worst_rows.append(
                f"| {label} | {years}yr | {wdate} | ${w[f'{strat.name} Total Invested']:,.0f} "
                f"| ${w[f'{strat.name} Final Value']:,.0f} | {w[f'{strat.name} Total ROI (%)']:.0f}% "
                f"| {w[f'{strat.name} Max DD (%)']:.1f}% |")

    doc = f"""# DCA Contribution Analysis — Two Accounts (2026-08-28)

How the production strategy plays out under the real contribution plan, split
across the two account types, each with its correct config and tax treatment.

- **Tax-advantaged**: $100,000 start + $35,000/year → **config D** (dual-signal
  + trailing stop 8%/60d), pre-tax.
- **Taxable**: $10,000 start + $2,000/month → **config C** (dual-signal, no
  stop), after-tax.

Base: 3× TQQQ (^NDX returns, S&P 500 signal), rolling windows stepped monthly
across the full history (dot-com, 2008, COVID, 2022 all included). Generated by
`backtest/dca_contribution_analysis.py`.

## Median outcome (typical window)

*Median across all rolling windows — what usually happens. Worst DD is the
deepest peak-to-trough of any single window.*

| Account | Horizon | Windows | Median Invested | Median Final | Median ROI | Worst DD | Avg TWR |
| :-- | :-- | --: | --: | --: | --: | --: | --: |
{chr(10).join(median_rows)}

## Worst case (unluckiest starting window)

*The single rolling window with the lowest money-weighted ROI — i.e. starting
your contribution plan right before the worst crash in the data. This is the
tail you must be able to sit through, not a typical result.*

| Account | Horizon | Worst window start | Invested | Final value | ROI | Max DD |
| :-- | :-- | :-- | --: | --: | --: | --: |
{chr(10).join(worst_rows)}

## How to read this

- **The trailing stop assignment is correct.** In the tax-advantaged account
  (config D) worst-case drawdown holds near −62%; the taxable account (config C,
  no stop) runs near −86%. The stop is worth its return cost pre-tax and is a
  net-negative trade after tax — hence stop in tax-advantaged, none in taxable,
  the same rule for DCA and lump sum.
- **The two accounts do not diversify each other.** Both hold 3× NASDAQ
  exposure and move together; the worst-case drawdowns land in the same windows.
- **Median ≠ guaranteed.** The worst-case table shows how far a badly-timed
  start falls short of the median. Shorter horizons (5–10yr) have wide
  dispersion; the 26yr rows are the long-run anchor.
- **Nominal backtest figures, not a forecast.** The past four crashes are baked
  in; the next one is not. This is mechanical model output, **not personalized
  investment advice.**
"""
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(doc)
    # Print tables only (ASCII-safe); the full doc with arrows is in the file.
    print("\n".join(["MEDIAN:", *median_rows, "", "WORST:", *worst_rows]))
    print(f"\nWritten to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
